require "config.options"
require "config.keymaps"
require "config.plugins"

require "config.colorscheme"
require "config.cmp"
require "config.telescope"
require "config.treesitter"
require "config.nvim_tree"
require "config.lsp"
